version: '3' 
services:
  api:
    build: ./
    ports:
    - "49166:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
    depends_on:
      - db 
  db:
    image: mongo:latest
    ports:
      - "27018:27017" 
    volumes:
      - mongodata:/data/db 
volumes:
  mongodata: 